/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsBillingRouteImport } from './routes/clients.billing'
import { Route as ClientsDashboardRouteImport } from './routes/clients.dashboard'
import { Route as ClientsDocumentsRouteImport } from './routes/clients.documents'
import { Route as ClientsMessagesRouteImport } from './routes/clients.messages'
import { Route as ClientsNotificationsRouteImport } from './routes/clients.notifications'
import { Route as ClientsProfileRouteImport } from './routes/clients.profile'
import { Route as ClientsProjectsRouteImport } from './routes/clients.projects'
import { Route as ClientsSupportRouteImport } from './routes/clients.support'
import { Route as ClientsTasksRouteImport } from './routes/clients.tasks'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as TeamIndexRouteImport } from './routes/team.index'
import { Route as TeamSlugRouteImport } from './routes/team.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAboutRouteImport } from './routes/_authenticated/admin.about'
import { Route as AuthenticatedAdminBadgesRouteImport } from './routes/_authenticated/admin.badges'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin.bookings'
import { Route as AuthenticatedAdminCasesRouteImport } from './routes/_authenticated/admin.cases'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin.clients'
import { Route as AuthenticatedAdminCrmRouteImport } from './routes/_authenticated/admin.crm'
import { Route as AuthenticatedAdminFaqsRouteImport } from './routes/_authenticated/admin.faqs'
import { Route as AuthenticatedAdminInvoicesRouteImport } from './routes/_authenticated/admin.invoices'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin.messages'
import { Route as AuthenticatedAdminNewsletterRouteImport } from './routes/_authenticated/admin.newsletter'
import { Route as AuthenticatedAdminPixelsRouteImport } from './routes/_authenticated/admin.pixels'
import { Route as AuthenticatedAdminPortalRouteImport } from './routes/_authenticated/admin.portal'
import { Route as AuthenticatedAdminPortfolioRouteImport } from './routes/_authenticated/admin.portfolio'
import { Route as AuthenticatedAdminPricingRouteImport } from './routes/_authenticated/admin.pricing'
import { Route as AuthenticatedAdminProcessRouteImport } from './routes/_authenticated/admin.process'
import { Route as AuthenticatedAdminProposalsRouteImport } from './routes/_authenticated/admin.proposals'
import { Route as AuthenticatedAdminQuotesRouteImport } from './routes/_authenticated/admin.quotes'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated/admin.seo'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminStatsRouteImport } from './routes/_authenticated/admin.stats'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin.team'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated/admin.testimonials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsBillingRoute = ClientsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsDashboardRoute = ClientsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsDocumentsRoute = ClientsDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsMessagesRoute = ClientsMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsNotificationsRoute = ClientsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsProfileRoute = ClientsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsProjectsRoute = ClientsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsSupportRoute = ClientsSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsTasksRoute = ClientsTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ClientsRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamRoute,
} as any)
const TeamSlugRoute = TeamSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TeamRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAboutRoute = AuthenticatedAdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBadgesRoute =
  AuthenticatedAdminBadgesRouteImport.update({
    id: '/badges',
    path: '/badges',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCasesRoute = AuthenticatedAdminCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCrmRoute = AuthenticatedAdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFaqsRoute = AuthenticatedAdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminInvoicesRoute =
  AuthenticatedAdminInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNewsletterRoute =
  AuthenticatedAdminNewsletterRouteImport.update({
    id: '/newsletter',
    path: '/newsletter',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPixelsRoute =
  AuthenticatedAdminPixelsRouteImport.update({
    id: '/pixels',
    path: '/pixels',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPortalRoute =
  AuthenticatedAdminPortalRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPortfolioRoute =
  AuthenticatedAdminPortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPricingRoute =
  AuthenticatedAdminPricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProcessRoute =
  AuthenticatedAdminProcessRouteImport.update({
    id: '/process',
    path: '/process',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProposalsRoute =
  AuthenticatedAdminProposalsRouteImport.update({
    id: '/proposals',
    path: '/proposals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuotesRoute =
  AuthenticatedAdminQuotesRouteImport.update({
    id: '/quotes',
    path: '/quotes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStatsRoute = AuthenticatedAdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/calculator': typeof CalculatorRoute
  '/careers': typeof CareersRoute
  '/clients': typeof ClientsRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/clients/billing': typeof ClientsBillingRoute
  '/clients/dashboard': typeof ClientsDashboardRoute
  '/clients/documents': typeof ClientsDocumentsRoute
  '/clients/messages': typeof ClientsMessagesRoute
  '/clients/notifications': typeof ClientsNotificationsRoute
  '/clients/profile': typeof ClientsProfileRoute
  '/clients/projects': typeof ClientsProjectsRoute
  '/clients/support': typeof ClientsSupportRoute
  '/clients/tasks': typeof ClientsTasksRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/team/$slug': typeof TeamSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/team/': typeof TeamIndexRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/badges': typeof AuthenticatedAdminBadgesRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/cases': typeof AuthenticatedAdminCasesRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/pixels': typeof AuthenticatedAdminPixelsRoute
  '/admin/portal': typeof AuthenticatedAdminPortalRoute
  '/admin/portfolio': typeof AuthenticatedAdminPortfolioRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/admin/process': typeof AuthenticatedAdminProcessRoute
  '/admin/proposals': typeof AuthenticatedAdminProposalsRoute
  '/admin/quotes': typeof AuthenticatedAdminQuotesRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/calculator': typeof CalculatorRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/clients/billing': typeof ClientsBillingRoute
  '/clients/dashboard': typeof ClientsDashboardRoute
  '/clients/documents': typeof ClientsDocumentsRoute
  '/clients/messages': typeof ClientsMessagesRoute
  '/clients/notifications': typeof ClientsNotificationsRoute
  '/clients/profile': typeof ClientsProfileRoute
  '/clients/projects': typeof ClientsProjectsRoute
  '/clients/support': typeof ClientsSupportRoute
  '/clients/tasks': typeof ClientsTasksRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/team/$slug': typeof TeamSlugRoute
  '/blog': typeof BlogIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/team': typeof TeamIndexRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/badges': typeof AuthenticatedAdminBadgesRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/cases': typeof AuthenticatedAdminCasesRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/pixels': typeof AuthenticatedAdminPixelsRoute
  '/admin/portal': typeof AuthenticatedAdminPortalRoute
  '/admin/portfolio': typeof AuthenticatedAdminPortfolioRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/admin/process': typeof AuthenticatedAdminProcessRoute
  '/admin/proposals': typeof AuthenticatedAdminProposalsRoute
  '/admin/quotes': typeof AuthenticatedAdminQuotesRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/calculator': typeof CalculatorRoute
  '/careers': typeof CareersRoute
  '/clients': typeof ClientsRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRouteWithChildren
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/clients/billing': typeof ClientsBillingRoute
  '/clients/dashboard': typeof ClientsDashboardRoute
  '/clients/documents': typeof ClientsDocumentsRoute
  '/clients/messages': typeof ClientsMessagesRoute
  '/clients/notifications': typeof ClientsNotificationsRoute
  '/clients/profile': typeof ClientsProfileRoute
  '/clients/projects': typeof ClientsProjectsRoute
  '/clients/support': typeof ClientsSupportRoute
  '/clients/tasks': typeof ClientsTasksRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/team/$slug': typeof TeamSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/team/': typeof TeamIndexRoute
  '/_authenticated/admin/about': typeof AuthenticatedAdminAboutRoute
  '/_authenticated/admin/badges': typeof AuthenticatedAdminBadgesRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/cases': typeof AuthenticatedAdminCasesRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/_authenticated/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/_authenticated/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/_authenticated/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/_authenticated/admin/pixels': typeof AuthenticatedAdminPixelsRoute
  '/_authenticated/admin/portal': typeof AuthenticatedAdminPortalRoute
  '/_authenticated/admin/portfolio': typeof AuthenticatedAdminPortfolioRoute
  '/_authenticated/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/_authenticated/admin/process': typeof AuthenticatedAdminProcessRoute
  '/_authenticated/admin/proposals': typeof AuthenticatedAdminProposalsRoute
  '/_authenticated/admin/quotes': typeof AuthenticatedAdminQuotesRoute
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/stats': typeof AuthenticatedAdminStatsRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/audit'
    | '/auth'
    | '/book'
    | '/calculator'
    | '/careers'
    | '/clients'
    | '/contact'
    | '/faq'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/quote'
    | '/services'
    | '/sitemap.xml'
    | '/team'
    | '/terms'
    | '/admin'
    | '/api/chat'
    | '/blog/$slug'
    | '/clients/billing'
    | '/clients/dashboard'
    | '/clients/documents'
    | '/clients/messages'
    | '/clients/notifications'
    | '/clients/profile'
    | '/clients/projects'
    | '/clients/support'
    | '/clients/tasks'
    | '/services/$slug'
    | '/team/$slug'
    | '/blog/'
    | '/clients/'
    | '/services/'
    | '/team/'
    | '/admin/about'
    | '/admin/badges'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/cases'
    | '/admin/clients'
    | '/admin/crm'
    | '/admin/faqs'
    | '/admin/invoices'
    | '/admin/messages'
    | '/admin/newsletter'
    | '/admin/pixels'
    | '/admin/portal'
    | '/admin/portfolio'
    | '/admin/pricing'
    | '/admin/process'
    | '/admin/proposals'
    | '/admin/quotes'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/stats'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/audit'
    | '/auth'
    | '/book'
    | '/calculator'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/quote'
    | '/sitemap.xml'
    | '/terms'
    | '/api/chat'
    | '/blog/$slug'
    | '/clients/billing'
    | '/clients/dashboard'
    | '/clients/documents'
    | '/clients/messages'
    | '/clients/notifications'
    | '/clients/profile'
    | '/clients/projects'
    | '/clients/support'
    | '/clients/tasks'
    | '/services/$slug'
    | '/team/$slug'
    | '/blog'
    | '/clients'
    | '/services'
    | '/team'
    | '/admin/about'
    | '/admin/badges'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/cases'
    | '/admin/clients'
    | '/admin/crm'
    | '/admin/faqs'
    | '/admin/invoices'
    | '/admin/messages'
    | '/admin/newsletter'
    | '/admin/pixels'
    | '/admin/portal'
    | '/admin/portfolio'
    | '/admin/pricing'
    | '/admin/process'
    | '/admin/proposals'
    | '/admin/quotes'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/stats'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/audit'
    | '/auth'
    | '/book'
    | '/calculator'
    | '/careers'
    | '/clients'
    | '/contact'
    | '/faq'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/quote'
    | '/services'
    | '/sitemap.xml'
    | '/team'
    | '/terms'
    | '/_authenticated/admin'
    | '/api/chat'
    | '/blog/$slug'
    | '/clients/billing'
    | '/clients/dashboard'
    | '/clients/documents'
    | '/clients/messages'
    | '/clients/notifications'
    | '/clients/profile'
    | '/clients/projects'
    | '/clients/support'
    | '/clients/tasks'
    | '/services/$slug'
    | '/team/$slug'
    | '/blog/'
    | '/clients/'
    | '/services/'
    | '/team/'
    | '/_authenticated/admin/about'
    | '/_authenticated/admin/badges'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/cases'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/crm'
    | '/_authenticated/admin/faqs'
    | '/_authenticated/admin/invoices'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/newsletter'
    | '/_authenticated/admin/pixels'
    | '/_authenticated/admin/portal'
    | '/_authenticated/admin/portfolio'
    | '/_authenticated/admin/pricing'
    | '/_authenticated/admin/process'
    | '/_authenticated/admin/proposals'
    | '/_authenticated/admin/quotes'
    | '/_authenticated/admin/seo'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/stats'
    | '/_authenticated/admin/team'
    | '/_authenticated/admin/testimonials'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  CalculatorRoute: typeof CalculatorRoute
  CareersRoute: typeof CareersRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRouteWithChildren
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/billing': {
      id: '/clients/billing'
      path: '/billing'
      fullPath: '/clients/billing'
      preLoaderRoute: typeof ClientsBillingRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/dashboard': {
      id: '/clients/dashboard'
      path: '/dashboard'
      fullPath: '/clients/dashboard'
      preLoaderRoute: typeof ClientsDashboardRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/documents': {
      id: '/clients/documents'
      path: '/documents'
      fullPath: '/clients/documents'
      preLoaderRoute: typeof ClientsDocumentsRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/messages': {
      id: '/clients/messages'
      path: '/messages'
      fullPath: '/clients/messages'
      preLoaderRoute: typeof ClientsMessagesRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/notifications': {
      id: '/clients/notifications'
      path: '/notifications'
      fullPath: '/clients/notifications'
      preLoaderRoute: typeof ClientsNotificationsRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/profile': {
      id: '/clients/profile'
      path: '/profile'
      fullPath: '/clients/profile'
      preLoaderRoute: typeof ClientsProfileRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/projects': {
      id: '/clients/projects'
      path: '/projects'
      fullPath: '/clients/projects'
      preLoaderRoute: typeof ClientsProjectsRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/support': {
      id: '/clients/support'
      path: '/support'
      fullPath: '/clients/support'
      preLoaderRoute: typeof ClientsSupportRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/tasks': {
      id: '/clients/tasks'
      path: '/tasks'
      fullPath: '/clients/tasks'
      preLoaderRoute: typeof ClientsTasksRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/team/': {
      id: '/team/'
      path: '/'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/$slug': {
      id: '/team/$slug'
      path: '/$slug'
      fullPath: '/team/$slug'
      preLoaderRoute: typeof TeamSlugRouteImport
      parentRoute: typeof TeamRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/about': {
      id: '/_authenticated/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AuthenticatedAdminAboutRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/badges': {
      id: '/_authenticated/admin/badges'
      path: '/badges'
      fullPath: '/admin/badges'
      preLoaderRoute: typeof AuthenticatedAdminBadgesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cases': {
      id: '/_authenticated/admin/cases'
      path: '/cases'
      fullPath: '/admin/cases'
      preLoaderRoute: typeof AuthenticatedAdminCasesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/crm': {
      id: '/_authenticated/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AuthenticatedAdminCrmRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/faqs': {
      id: '/_authenticated/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AuthenticatedAdminFaqsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invoices': {
      id: '/_authenticated/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/newsletter': {
      id: '/_authenticated/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AuthenticatedAdminNewsletterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pixels': {
      id: '/_authenticated/admin/pixels'
      path: '/pixels'
      fullPath: '/admin/pixels'
      preLoaderRoute: typeof AuthenticatedAdminPixelsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/portal': {
      id: '/_authenticated/admin/portal'
      path: '/portal'
      fullPath: '/admin/portal'
      preLoaderRoute: typeof AuthenticatedAdminPortalRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/portfolio': {
      id: '/_authenticated/admin/portfolio'
      path: '/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AuthenticatedAdminPortfolioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pricing': {
      id: '/_authenticated/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AuthenticatedAdminPricingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/process': {
      id: '/_authenticated/admin/process'
      path: '/process'
      fullPath: '/admin/process'
      preLoaderRoute: typeof AuthenticatedAdminProcessRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/proposals': {
      id: '/_authenticated/admin/proposals'
      path: '/proposals'
      fullPath: '/admin/proposals'
      preLoaderRoute: typeof AuthenticatedAdminProposalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/quotes': {
      id: '/_authenticated/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AuthenticatedAdminQuotesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/stats': {
      id: '/_authenticated/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AuthenticatedAdminStatsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAboutRoute: typeof AuthenticatedAdminAboutRoute
  AuthenticatedAdminBadgesRoute: typeof AuthenticatedAdminBadgesRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminCasesRoute: typeof AuthenticatedAdminCasesRoute
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRoute
  AuthenticatedAdminCrmRoute: typeof AuthenticatedAdminCrmRoute
  AuthenticatedAdminFaqsRoute: typeof AuthenticatedAdminFaqsRoute
  AuthenticatedAdminInvoicesRoute: typeof AuthenticatedAdminInvoicesRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminNewsletterRoute: typeof AuthenticatedAdminNewsletterRoute
  AuthenticatedAdminPixelsRoute: typeof AuthenticatedAdminPixelsRoute
  AuthenticatedAdminPortalRoute: typeof AuthenticatedAdminPortalRoute
  AuthenticatedAdminPortfolioRoute: typeof AuthenticatedAdminPortfolioRoute
  AuthenticatedAdminPricingRoute: typeof AuthenticatedAdminPricingRoute
  AuthenticatedAdminProcessRoute: typeof AuthenticatedAdminProcessRoute
  AuthenticatedAdminProposalsRoute: typeof AuthenticatedAdminProposalsRoute
  AuthenticatedAdminQuotesRoute: typeof AuthenticatedAdminQuotesRoute
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminStatsRoute: typeof AuthenticatedAdminStatsRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAboutRoute: AuthenticatedAdminAboutRoute,
  AuthenticatedAdminBadgesRoute: AuthenticatedAdminBadgesRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
  AuthenticatedAdminCasesRoute: AuthenticatedAdminCasesRoute,
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRoute,
  AuthenticatedAdminCrmRoute: AuthenticatedAdminCrmRoute,
  AuthenticatedAdminFaqsRoute: AuthenticatedAdminFaqsRoute,
  AuthenticatedAdminInvoicesRoute: AuthenticatedAdminInvoicesRoute,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminNewsletterRoute: AuthenticatedAdminNewsletterRoute,
  AuthenticatedAdminPixelsRoute: AuthenticatedAdminPixelsRoute,
  AuthenticatedAdminPortalRoute: AuthenticatedAdminPortalRoute,
  AuthenticatedAdminPortfolioRoute: AuthenticatedAdminPortfolioRoute,
  AuthenticatedAdminPricingRoute: AuthenticatedAdminPricingRoute,
  AuthenticatedAdminProcessRoute: AuthenticatedAdminProcessRoute,
  AuthenticatedAdminProposalsRoute: AuthenticatedAdminProposalsRoute,
  AuthenticatedAdminQuotesRoute: AuthenticatedAdminQuotesRoute,
  AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminStatsRoute: AuthenticatedAdminStatsRoute,
  AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
  AuthenticatedAdminTestimonialsRoute: AuthenticatedAdminTestimonialsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClientsRouteChildren {
  ClientsBillingRoute: typeof ClientsBillingRoute
  ClientsDashboardRoute: typeof ClientsDashboardRoute
  ClientsDocumentsRoute: typeof ClientsDocumentsRoute
  ClientsMessagesRoute: typeof ClientsMessagesRoute
  ClientsNotificationsRoute: typeof ClientsNotificationsRoute
  ClientsProfileRoute: typeof ClientsProfileRoute
  ClientsProjectsRoute: typeof ClientsProjectsRoute
  ClientsSupportRoute: typeof ClientsSupportRoute
  ClientsTasksRoute: typeof ClientsTasksRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsBillingRoute: ClientsBillingRoute,
  ClientsDashboardRoute: ClientsDashboardRoute,
  ClientsDocumentsRoute: ClientsDocumentsRoute,
  ClientsMessagesRoute: ClientsMessagesRoute,
  ClientsNotificationsRoute: ClientsNotificationsRoute,
  ClientsProfileRoute: ClientsProfileRoute,
  ClientsProjectsRoute: ClientsProjectsRoute,
  ClientsSupportRoute: ClientsSupportRoute,
  ClientsTasksRoute: ClientsTasksRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface TeamRouteChildren {
  TeamSlugRoute: typeof TeamSlugRoute
  TeamIndexRoute: typeof TeamIndexRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamSlugRoute: TeamSlugRoute,
  TeamIndexRoute: TeamIndexRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  CalculatorRoute: CalculatorRoute,
  CareersRoute: CareersRoute,
  ClientsRoute: ClientsRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRouteWithChildren,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
